// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *AddArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Blob (datamodel.BlobModel) (struct)
	if len("blob") > 8192 {
		return fmt.Errorf("String in field \"blob\" was too long")
	}
	if err := jw.WriteString(string("blob")); err != nil {
		return fmt.Errorf("\"blob\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Blob.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Blob: %w", err)
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AddArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AddArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("AddArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("AddArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("AddArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("AddArgumentsModel: string too large")
				}
				return fmt.Errorf("AddArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("AddArgumentsModel: %w", err)
			}
			switch name {

			// t.Blob (datamodel.BlobModel) (struct)
			case "blob":

				if err := t.Blob.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Blob: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("AddArgumentsModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("AddArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("AddArgumentsModel: map too large")
			}
		}
	}

	return nil
}
func (t *BlobModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Digest (multihash.Multihash) (slice)
	if len("digest") > 8192 {
		return fmt.Errorf("String in field \"digest\" was too long")
	}
	if err := jw.WriteString(string("digest")); err != nil {
		return fmt.Errorf("\"digest\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Digest) > 2097152 {
		return fmt.Errorf("Byte array in field t.Digest was too long")
	}

	if err := jw.WriteBytes(t.Digest); err != nil {
		return fmt.Errorf("t.Digest: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Size (uint64) (uint64)
	if len("size") > 8192 {
		return fmt.Errorf("String in field \"size\" was too long")
	}
	if err := jw.WriteString(string("size")); err != nil {
		return fmt.Errorf("\"size\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteUint64(uint64(t.Size)); err != nil {
		return fmt.Errorf("t.Size: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *BlobModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = BlobModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("BlobModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("BlobModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("BlobModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("BlobModel: string too large")
				}
				return fmt.Errorf("BlobModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("BlobModel: %w", err)
			}
			switch name {

			// t.Digest (multihash.Multihash) (slice)
			case "digest":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Digest: byte array too large")
						}
						return fmt.Errorf("t.Digest: %w", err)
					}
					if len(bval) > 0 {
						t.Digest = []uint8(bval)
					}
				}

				// t.Size (uint64) (uint64)
			case "size":
				{

					nval, err := jr.ReadNumberAsUint64()
					if err != nil {
						return fmt.Errorf("t.Size: %w", err)
					}
					t.Size = uint64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("BlobModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("BlobModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("BlobModel: map too large")
			}
		}
	}

	return nil
}
func (t *AddOKModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Site (promise.AwaitOK) (struct)
	if len("site") > 8192 {
		return fmt.Errorf("String in field \"site\" was too long")
	}
	if err := jw.WriteString(string("site")); err != nil {
		return fmt.Errorf("\"site\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Site.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Site: %w", err)
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AddOKModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AddOKModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("AddOKModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("AddOKModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("AddOKModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("AddOKModel: string too large")
				}
				return fmt.Errorf("AddOKModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("AddOKModel: %w", err)
			}
			switch name {

			// t.Site (promise.AwaitOK) (struct)
			case "site":

				if err := t.Site.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Site: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("AddOKModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("AddOKModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("AddOKModel: map too large")
			}
		}
	}

	return nil
}
